Itanio.Marketplace.WebUI/Controllers/SaleController.cs
using System.Net.Mail;
using System.Web.Mvc;
using Itanio.Marketplace.Domain;
using Itanio.Marketplace.WebUI.Models;
using PagarMe;

namespace Itanio.Marketplace.WebUI.Controllers
{
    public class SaleController : BaseController
    {
        public SaleController(IDbContext context)
            : base(context)
        {
        }

        // GET: Sale
        public ActionResult Index(int id)
        {
            var product = _context.Products.Find(id);
            return View(ProductViewModel.FromEntity(product));
        }

        [HttpPost]
        public ActionResult Buy(BuyViewModel viewModel)
        {
            PagarMeService.DefaultApiKey = "ak_test_lgKqOTGfDasjTSNYfXvrzMuaQWwmGE";
            var transaction = PagarMeService.GetDefaultService().Transactions.Find(viewModel.Token);
            transaction.Capture(transaction.Amount);
            TempData["transaction"] = transaction;
            return RedirectToAction(transaction.Status.ToString());
        }

        public ActionResult Paid()
        {
            var transaction = (Transaction) TempData["transaction"];
            //SendEmail(transaction);
            return View();
        }

        public ActionResult WaitingPayment()
        {
            var transaction = (Transaction) TempData["transaction"];
            //SendEmail(transaction);
            return Redirect(transaction.BoletoUrl);
        }

        public ActionResult Refused()
        {
            var transaction = (Transaction) TempData["transaction"];
            //SendEmail(transaction);
            return View();
        }

        private void SendEmail(Transaction transaction)
        {
            var smtpClient = new SmtpClient();
            var message = new MailMessage();

            message.Body = RenderRazorViewToString($"Email{transaction.Status}", transaction);
            message.To.Add(transaction.Customer.Email);
            message.From = new MailAddress("vendas@itanio.com.br");
            message.IsBodyHtml = true;
            message.Priority = MailPriority.Normal;
            smtpClient.Send(message);
        }
    }
}

Itanio.Marketplace.WebUI/Views/Sale/EmailPaid.cshtml
@model PagarMe.Transaction
@{
    Layout = "_EmailLayout.cshtml";
}

Itanio.Marketplace.WebUI/Views/Sale/EmailRefused.cshtml
@model PagarMe.Transaction

Itanio.Marketplace.WebUI/Views/Sale/EmailWaitingPayment.cshtml
@model PagarMe.Transaction
@{
    Layout = "_EmailLayout.cshtml";
}

Itanio.Marketplace.WebUI/Views/Sale/Index.cshtml
@model Itanio.Marketplace.WebUI.Models.ProductViewModel
@{
    Layout = "_layout.cshtml";
    ViewBag.Title = Model.Name;
}
<div class="row">
    <div class="box col-lg-10 col-sm-10 col-sm-offset-1 col-xs-12">
        <label>Verifique as informações do produto abaixo</label>
        <hr/>
        <h3>@Html.DisplayFor(model => model.Name)</h3>

        <p> @Html.DisplayFor(model => model.Description)</p>
        <h4>
            @Html.DisplayFor(model => model.Ammount)
            @if (Model.MaxStallments > 1)
            {
                @($"em até {Model.MaxStallments}x")
            }
        </h4>

        <div class="text-center">
            @using (Html.BeginForm("Buy", "Sale"))
            {
                <script type="text/javascript"
                        src="https://assets.pagar.me/checkout/checkout.js"
                        data-button-text="@Model.StartButtonText"
                        data-button-class="btn btn-primary"
                        data-customer-data="@Model.CustomerDataRequired.ToString().ToLower()"
                        data-payment-methods="@Model.PaymentMethods.Description()"
                        data-encryption-key="ek_test_6kfQBymU7aITL4XcbczwO7qSC0Ih4M"
                        data-max-installments="@Model.MaxStallments"
                        data-header-text="@Model.HeaderText"
                        data-payment-button-text="@Model.EndButtonText"
                        data-amount="@Model.Ammount.ToString().Replace(",", string.Empty)" data-ui-color="#eb8a0f">
                </script>
            }
        </div>
    </div>
</div>
<div class="row">
    @Html.Partial("_NavegacaoSeguraInfo")
</div>

Itanio.Marketplace.WebUI/Views/Sale/Paid.cshtml
@model PagarMe.Transaction
@{
    Layout = "_layout.cshtml";
    ViewBag.Title = "Transação concluída com sucesso!";
}
<div class="row">
    <div class="box col-lg-10 col-sm-10 col-sm-offset-1 col-xs-12">
        <div class="row">
            <div class="col-xs-2 col-md-1">
                <img src="~/Content/images/paid.png" class="payment-icon"/>
            </div>
            <div class="col-xs-10 col-md-11">
                <h1>Transação concluída com sucesso!</h1>
            </div>
        </div>
        <hr/>
        <p>Você receberá um e-mail com as informações de seu pagamento em instantes.</p>
    </div>
</div>

Itanio.Marketplace.WebUI/Views/Sale/Refused.cshtml
@model PagarMe.Transaction
@{
    Layout = "_layout.cshtml";
    ViewBag.Title = "Ooopss... Houve um problema";
}
<div class="row">
    <div class="box col-lg-10 col-sm-10 col-sm-offset-1 col-xs-12">
        <div class="row">
            <div class="col-xs-2 col-md-1">
                <img src="~/Content/images/refused.png" class="payment-icon"/>
            </div>
            <div class="col-xs-10 col-md-11">
                <h1>Ooopss... Houve um problema</h1>
            </div>
        </div>
        <div class="col-xs-12">
            <hr/>
            <p class="text-justify">Por algum motivo sua operadora de cartões não aprovou a sua transação. Seguem sugestões:</p>
            <ol>
                <li>Ligue na operadora do seu cartão e veja se houve algum bloqueio nesta transação;</li>
                <li>Clique no botão voltar e efetue o pagamento utilizando boleto;</li>
                <li>Tente novamente mais tarde, pode ter ocorrido algum erro momentâneo de sistema;</li>
            </ol>
            <p class="text-justify">
                Nós enviamos por e-mail o resumo da sua transação e o link para o acesso a central de pagamentos da Itanio. Você pode tentar efetuar o pagamento novamente a qualquer momento.
            </p>
        </div>
    </div>
</div>

Itanio.Marketplace.WebUI/Views/Sale/WaitingPayment.cshtml
@model PagarMe.Transaction

Itanio.Marketplace.WebUI/Views/Sale/_EmailLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>_EmailLayout</title>
</head>
<body>
<div>
    @RenderBody()
</div>
</body>
</html>

Itanio.Marketplace.WebUI/Views/Sale/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    @Styles.Render("~/Content/salescss")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
</head>
<body>

<div id="overlay"></div>
<div id="second-overlay">
    <div id="header-panel">
        <div class="container">
            <div class="row">
                <div class="col-xs-10 col-sm-offset-1 col-sm-6  col-lg-7">
                    <h1>
                        Central on-line de pagamentos
                    </h1>
                </div>
                <div class="col-xs-2 col-sm-4 col-md-3 col-md-offset-1 col-lg-offset-0 text-right">
                    <h1>
                        LOGO
                    </h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>
</div>
@Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Itanio.Marketplace.WebUI/Views/Sale/_NavegacaoSeguraInfo.cshtml
<div class="box col-lg-10   col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="col-sm-9">
        <h4>Nosso compromisso com a segurança dos seu dados:</h4>
        <p class="text-justify">
            Você está navegando em ambiente seguro e controlado pela Itanio. Verifique sempre o endereço na barra de navegação, e tenha certeza que há a menção de nosso domínio itanio.com.br - Isso atesta que você está navegando realmente em nosso ambiente. Além disso, confira o valor apresentado na tela. Ao lado (ou abaixo) você pode visualizar também o selo de segurança da empresa THAWTE assegurando que o domínio itanio.com.br possui criptografia de dados, o que lhe garante maior confiabilidade, pois seus dados não trafegarão sem proteção pela internet. Todas as informações são criptografas.
        </p>
        <h4>
            Seus dados de cartão de crédito
        </h4>
        <p class="text-justify">
            A Itanio não armazena os dados de seu cartão de crédito. Você fará a digitação das informações, nós as enviaremos para a sua operadora para a validação, e o processo termina exatamente neste ponto. Dessa forma, além de não ficarmos em poder das informações, nós garantimos que os dados trafegarão entre a Itanio e a sua operadora totalmente criptografos, garantindo total segurança nas informações.
        </p>
    </div>
    <div class="col-sm-3">
        <h4 class="text-center">Selo de Segurança</h4>
        <div id="thawteseal" class="text-center" style="margin-top: 20px" title="Click to Verify - This site chose Thawte SSL for secure e-commerce and confidential communications.">
            <div>
                <script type="text/javascript" src="https://seal.thawte.com/getthawteseal?host_name=www.itanio.com.br&amp;size=L&amp;lang=br"></script>
                <a href="https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&amp;dn=www.itanio.com.br&amp;lang=br"
                   tabindex="-1"
                   onmousedown="return v_mDown(event);"
                   target="THAWTE_Splash">
                    <img name="seal"
                         border="true"
                         src="https://seal.thawte.com/getthawteseal?at=0&amp;sealid=1&amp;dn=www.itanio.com.br&amp;lang=br&amp;gmtoff=180"
                         oncontextmenu="return false;"
                         alt="Click to Verify - This site has chosen a thawte SSL Certificate to improve Web site security">
                </a>
            </div>
        </div>
        <div class="text-center" style="margin-top: 20px">
            Caso queira, clique no selo acima para visualizar as informações de registro da Itanio no serviço de criptografia da empresa Thawte de segurança digital.
        </div>
    </div>
</div>